parsers:
- ./parsers/s01-parse/crowdsecurity/proftpd-logs.yaml
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- ./scenarios/crowdsecurity/proftpd-bf.yaml
postoverflows:
- ""
log_file: proftpd-bf.log
log_type: proftpd
labels: {}
ignore_parsers: true
