parsers:
- ./parsers/s01-parse/crowdsecurity/proftpd-logs.yaml
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- ""
postoverflows:
- ""
log_file: proftpd-logs.log
log_type: proftpd
labels: {}
ignore_parsers: false
